In [1]:
import numpy as np
import gym

In [2]:
# env = gym.make('CartPole-v0')
# env.reset()
# for _ in range(1000):
#     env.render()
#     env.step(env.action_space.sample()) # take a random action
# env.close()

In [2]:
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[ 0.0108705  -0.03593922  0.04122373 -0.00637236]
[ 0.01015171  0.15856802  0.04109628 -0.285769  ]
[ 0.01332307  0.35308051  0.0353809  -0.56521247]
[ 0.02038468  0.54768868  0.02407665 -0.84654222]
[ 0.03133846  0.74247404  0.00714581 -1.13155772]
[ 0.04618794  0.54725926 -0.01548535 -0.83664219]
[ 0.05713312  0.3523522  -0.03221819 -0.54886916]
[ 0.06418017  0.54791158 -0.04319557 -0.8515265 ]
[ 0.0751384   0.35340433 -0.0602261  -0.57273334]
[ 0.08220648  0.15917625 -0.07168077 -0.2996152 ]
[ 0.08539001  0.35524283 -0.07767307 -0.61401594]
[ 0.09249487  0.16128726 -0.08995339 -0.34677268]
[ 0.09572061 -0.03244772 -0.09688885 -0.08375579]
[ 0.09507166  0.16391996 -0.09856396 -0.40536661]
[ 0.09835006 -0.02967618 -0.10667129 -0.14531274]
[ 0.09775653  0.16679885 -0.10957755 -0.46965207]
[ 0.10109251 -0.02661843 -0.11897059 -0.21341759]
[ 0.10056014 -0.21985631 -0.12323894  0.03949544]
[ 0.09616301 -0.0232024  -0.12244903 -0.28938881]
[ 0.09569897 -0.21638484 -0.12823681 -0.03769494]


[-0.02377034  0.77921967  0.05788049 -0.99086186]
[-0.00818595  0.58337284  0.03806325 -0.68057621]
[ 0.00348151  0.38774346  0.02445173 -0.37615679]
[ 0.01123638  0.1922829   0.01692859 -0.0758655 ]
[ 0.01508204  0.38715813  0.01541128 -0.36315969]
[ 0.0228252   0.19182057  0.00814809 -0.06565741]
[ 0.02666161 -0.00341725  0.00683494  0.22958511]
[ 0.02659326 -0.1986362   0.01142664  0.52441616]
[ 0.02262054 -0.39391708  0.02191497  0.82067772]
[ 0.0147422  -0.19910177  0.03832852  0.5349674 ]
[ 0.01076016 -0.00453917  0.04902787  0.25460367]
[ 0.01066938  0.18984971  0.05411994 -0.02222086]
[ 0.01446637  0.38415544  0.05367552 -0.29734923]
[ 0.02214948  0.57847279  0.04772854 -0.57263244]
[ 0.03371894  0.77289416  0.03627589 -0.84990553]
[ 0.04917682  0.5772968   0.01927778 -0.54603974]
[ 0.06072276  0.38190937  0.00835699 -0.24734573]
[ 0.06836095  0.57691098  0.00341007 -0.537381  ]
[ 0.07989916  0.38174125 -0.00733755 -0.24362555]
[ 0.08753399  0.57696723 -0.01221006 -0.53861386]


[ 0.22320206  0.98047422 -0.2091218  -1.72762787]
Episode finished after 34 timesteps
[-0.04499337 -0.00159589  0.0381976   0.03939738]
[-0.04502529  0.19295808  0.03898555 -0.24099334]
[-0.04116613 -0.00269846  0.03416568  0.06372732]
[-0.0412201  -0.19829318  0.03544023  0.36699093]
[-0.04518596 -0.00369229  0.04278005  0.08569014]
[-0.04525981 -0.19940052  0.04449385  0.3915574 ]
[-0.04924782 -0.00493733  0.052325    0.11322818]
[-0.04934657 -0.20076848  0.05458956  0.4219494 ]
[-0.05336194 -0.39661963  0.06302855  0.73132986]
[-0.06129433 -0.20242272  0.07765515  0.45913103]
[-0.06534278 -0.00847943  0.08683777  0.19190049]
[-0.06551237 -0.20472939  0.09067578  0.51066443]
[-0.06960696 -0.01099394  0.10088906  0.24787729]
[-0.06982684 -0.20740117  0.10584661  0.57060113]
[-0.07397486 -0.40383581  0.11725863  0.8946649 ]
[-0.08205158 -0.60033591  0.13515193  1.22178611]
[-0.0940583  -0.79691525  0.15958765  1.55357998]
[-0.1099966  -0.99354973  0.19065925  1.89150359]
Episode finish

In [5]:
parameters = np.random.rand(4) * 2 - 1
parameters

array([ 0.31808255,  0.41931817,  0.97397313, -0.23849917])

In [31]:
action = 0 if np.matmul(parameters,observation) < 0 else 1  

In [34]:
def run_episode(env, parameters):  
    observation = env.reset()
    totalreward = 0
    for _ in range(200):
        action = 0 if np.matmul(parameters,observation) < 0 else 1
        observation, reward, done, info = env.step(action)
        totalreward += reward
        if done:
            break
    return totalreward

In [46]:
# check how action looks
env.step(action)

(array([-2.29179637, -5.10907375,  1.5918507 ,  7.87765687]),
 0.0,
 True,
 {'TimeLimit.truncated': False})

2 techniques: Random Search and Hill-Climbing

In [17]:
# Random Search
bestparams = None  
bestreward = 0  
for _ in range(10000):  
    parameters = np.random.rand(4) * 2 - 1
    reward = run_episode(env,parameters)
    if reward > bestreward:
        bestreward = reward
        bestparams = parameters
        # considered solved if the agent lasts 200 timesteps
        if reward == 200:
            break

In [48]:
# Hill-Climbing
noise_scaling = 0.1  
parameters = np.random.rand(4) * 2 - 1  
bestreward = 0  
for _ in range(10000):  
    newparams = parameters + (np.random.rand(4) * 2 - 1)*noise_scaling
    reward = 0
    run = run_episode(env,newparams)
    if reward > bestreward:
        bestreward = reward
        parameters = newparams
        if reward == 200:
            break